/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        /** Health Head */
        head: operations["health_head_api_v1_health_head"];
        patch?: never;
        trace?: never;
    };
    "/api/v1/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Examples */
        get: operations["list_examples_api_v1_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analyses */
        get: operations["get_analyses_api_v1_analyses_get"];
        put?: never;
        /** Create Analysis */
        post: operations["create_analysis_api_v1_analyses_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis */
        get: operations["get_analysis_api_v1_analyses__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/analyses/{job_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analysis Result */
        get: operations["get_analysis_result_api_v1_analyses__job_id__result_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnalysisResult */
        AnalysisResult: {
            /** Case Slug */
            case_slug: string;
            /** Summary */
            summary: string;
            selected_base_repo: components["schemas"]["BaseRepoCandidate"];
            /** Base Repo Candidates */
            base_repo_candidates: components["schemas"]["BaseRepoCandidate"][];
            /** Contributions */
            contributions: components["schemas"]["PaperContribution"][];
            /** Diff Clusters */
            diff_clusters: components["schemas"]["DiffCluster"][];
            /** Mappings */
            mappings: components["schemas"]["ContributionMapping"][];
            /** Unmatched Contribution Ids */
            unmatched_contribution_ids?: string[];
            /** Unmatched Diff Cluster Ids */
            unmatched_diff_cluster_ids?: string[];
            metadata: components["schemas"]["AnalysisRuntimeMetadata"];
            /** Warnings */
            warnings: string[];
        };
        /** AnalysisRuntimeMetadata */
        AnalysisRuntimeMetadata: {
            paper_source_kind: components["schemas"]["PaperSourceKind"];
            paper_fetch_mode: components["schemas"]["ProcessorMode"];
            parser_mode: components["schemas"]["ProcessorMode"];
            repo_tracer_mode: components["schemas"]["ProcessorMode"];
            diff_analyzer_mode: components["schemas"]["ProcessorMode"];
            contribution_mapper_mode: components["schemas"]["ProcessorMode"];
            /** Selected Repo Strategy */
            selected_repo_strategy: string;
            /** Fallback Notes */
            fallback_notes: string[];
        };
        /** BaseRepoCandidate */
        BaseRepoCandidate: {
            /** Repo Url */
            repo_url: string;
            /** Strategy */
            strategy: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string;
        };
        /** ContributionMapping */
        ContributionMapping: {
            /** Diff Cluster Id */
            diff_cluster_id: string;
            /** Contribution Id */
            contribution_id: string;
            /** Confidence */
            confidence: number;
            /** Evidence */
            evidence: string;
            /** Completeness */
            completeness: string;
            /**
             * Implementation Coverage
             * @default 0
             */
            implementation_coverage: number;
            /**
             * Snippet Fidelity
             * @default 0
             */
            snippet_fidelity: number;
            /**
             * Formula Fidelity
             * @default 0
             */
            formula_fidelity: number;
            /** @default PARTIAL */
            coverage_type: components["schemas"]["CoverageType"];
            /** Missing Aspects */
            missing_aspects?: string[];
            /** Engineering Divergences */
            engineering_divergences?: string[];
            /** Fidelity Notes */
            fidelity_notes?: string[];
            /** Matched Anchor Patch Ids */
            matched_anchor_patch_ids?: string[];
            /** Learning Entry Point */
            learning_entry_point?: string | null;
            /** Reading Order */
            reading_order?: string[];
        };
        /**
         * CoverageType
         * @enum {string}
         */
        CoverageType: "FULL" | "PARTIAL" | "APPROXIMATED" | "MISSING";
        /** CreateAnalysisResponse */
        CreateAnalysisResponse: {
            job: components["schemas"]["JobStatusResponse"];
        };
        /**
         * DiffChangeType
         * @enum {string}
         */
        DiffChangeType: "NEW_MODULE" | "MODIFIED_CORE" | "MODIFIED_LOSS" | "MODIFIED_TRAIN" | "MODIFIED_INFRA";
        /** DiffCluster */
        DiffCluster: {
            /** Id */
            id: string;
            /** Patch Id */
            patch_id?: string | null;
            /** Label */
            label: string;
            change_type: components["schemas"]["DiffChangeType"];
            /** Files */
            files: string[];
            /** Summary */
            summary: string;
            /** Code Anchors */
            code_anchors?: components["schemas"]["DiffCodeAnchor"][];
            /** Semantic Tags */
            semantic_tags?: string[];
            /** Related Cluster Ids */
            related_cluster_ids?: string[];
        };
        /** DiffCodeAnchor */
        DiffCodeAnchor: {
            /** Patch Id */
            patch_id?: string | null;
            /** File Path */
            file_path: string;
            /** Original File Path */
            original_file_path?: string | null;
            /** Start Line */
            start_line: number;
            /** End Line */
            end_line: number;
            /** Original Start Line */
            original_start_line?: number | null;
            /** Original End Line */
            original_end_line?: number | null;
            /** Snippet */
            snippet: string;
            /** Original Snippet */
            original_snippet?: string | null;
            /** Reason */
            reason: string;
            /** Anchor Kind */
            anchor_kind: string;
        };
        /** ExamplesResponse */
        ExamplesResponse: {
            /** Examples */
            examples: components["schemas"]["GoldenCaseExample"][];
        };
        /** GoldenCaseExample */
        GoldenCaseExample: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Paper Source */
            paper_source: string;
            /** Repo Url */
            repo_url: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Database */
            database: string;
            /** Queue Mode */
            queue_mode: string;
            /** Live By Default */
            live_by_default: boolean;
            /** Live Paper Fetch */
            live_paper_fetch: boolean;
            /** Live Repo Trace */
            live_repo_trace: boolean;
            /** Live Repo Analysis */
            live_repo_analysis: boolean;
            /** Llm Configured */
            llm_configured: boolean;
            /** Supported Paper Source Kinds */
            supported_paper_source_kinds: components["schemas"]["PaperSourceKind"][];
        };
        /**
         * JobStage
         * @enum {string}
         */
        JobStage: "paper_fetch" | "paper_parse" | "repo_fetch" | "ancestry_trace" | "diff_analyze" | "contribution_map" | "persist_result";
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "queued" | "running" | "succeeded" | "failed";
        /** JobStatusResponse */
        JobStatusResponse: {
            /** Id */
            id: string;
            status: components["schemas"]["JobStatus"];
            stage?: components["schemas"]["JobStage"] | null;
            /** Stage Progress */
            stage_progress?: number | null;
            /** Stage Detail */
            stage_detail?: string | null;
            /** Paper Source */
            paper_source: string;
            /** Repo Url */
            repo_url: string;
            /** Summary */
            summary?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Timeline */
            timeline?: components["schemas"]["JobTelemetryEvent"][];
            /** Result Available */
            result_available: boolean;
        };
        /** JobTelemetryEvent */
        JobTelemetryEvent: {
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            status: components["schemas"]["JobStatus"];
            stage?: components["schemas"]["JobStage"] | null;
            /** Progress */
            progress?: number | null;
            /** Detail */
            detail?: string | null;
        };
        /** JobsResponse */
        JobsResponse: {
            /** Jobs */
            jobs: components["schemas"]["JobStatusResponse"][];
        };
        /** PaperContribution */
        PaperContribution: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Section */
            section: string;
            /** Keywords */
            keywords: string[];
            /** Impl Hints */
            impl_hints: string[];
            /** Problem Solved */
            problem_solved?: string | null;
            /** Baseline Difference */
            baseline_difference?: string | null;
            /** Evidence Refs */
            evidence_refs?: string[];
            /** Implementation Complexity */
            implementation_complexity?: number | null;
        };
        /**
         * PaperSourceKind
         * @enum {string}
         */
        PaperSourceKind: "arxiv" | "pdf_url" | "pdf_file" | "text_reference";
        /**
         * ProcessorMode
         * @enum {string}
         */
        ProcessorMode: "remote_fetch" | "heuristic" | "llm" | "strategy_chain" | "fixture";
        /** ResultResponse */
        ResultResponse: {
            result: components["schemas"]["AnalysisResult"];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    health_head_api_v1_health_head: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_examples_api_v1_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExamplesResponse"];
                };
            };
        };
    };
    get_analyses_api_v1_analyses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobsResponse"];
                };
            };
        };
    };
    create_analysis_api_v1_analyses_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    repo_url?: string;
                    paper_input: {
                        /** @constant */
                        source_kind: "arxiv";
                        source_ref: string;
                    } | {
                        /** @constant */
                        source_kind: "pdf_url";
                        source_ref: string;
                    } | {
                        /** @constant */
                        source_kind: "text_reference";
                        source_ref: string;
                    };
                };
                "multipart/form-data": {
                    /** @description JSON-encoded paper source envelope. Use source_kind=pdf_file together with paper_file uploads. */
                    paper_input?: string;
                    /** @description arXiv URL, PDF URL, or optional text hint when uploading a PDF */
                    paper_source?: string;
                    /**
                     * @description Optional explicit source-kind hint for non-file submissions.
                     * @enum {string}
                     */
                    paper_source_kind?: "arxiv" | "pdf_url" | "pdf_file" | "text_reference";
                    repo_url?: string;
                    /** Format: binary */
                    paper_file?: string;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
        };
    };
    get_analysis_api_v1_analyses__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateAnalysisResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analysis_result_api_v1_analyses__job_id__result_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResultResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
